### ISSUE TITLE
duel wield gold deagles

### ISSUE THREAD

**Issue by david-wm-sanders** [rwr-community-dev/HB1#11]

**Comment by RubberyChickens** [comment]
8/27 progress:

*Basic weapon stats (less accuracy, stance accuracy mods were whichever was worse between the dualist and the normal G Deagle.)
*Shirtless Duke Nukem model (using it as a base to make the normal model, couldn't think of any better characters for dual Golden Deagles.)

TODO:
*Balance gun
*make more skins (same amount of skins as Dualist, ideally)

Weapon is functional, but requires additional models.  Like the dualist, the left hand pistol has to be added to the model itself.  As it is larger than the dualist, I'm not sure if it'll have clipping issues.

**Comment by RubberyChickens** [comment]
Another update, with a large problem.  Voxel weapons don't have an outline, but player models (unless you change settings?) do.  So, despite making sure the gun attached to the player model matches the original golden desert eagle, they look mismatched and awful.

Asking for advice from #modding and anyone else who might have a solution. Otherwise this gun is dead in the water.  If a gun looks bad on default settings, then it should not be in a CB.

![20210827195149_1](https://user-images.githubusercontent.com/58443311/131200117-f38041d1-8c69-4df0-b5b0-9d3f05f55e2b.jpg)

**Comment by RubberyChickens** [comment]
confirmed from the maker of the L30P that the outline problem is only solvable by making the guns near black.  As such *golden* dual desert eagles are impossible to make in a manner that looks good.  

I might reuse the files and make a dual blackout desert eagles or something, but consider the golden deagles withdrawn as a cb7 submission.
